all done
provan/zenmoney.plugins pull request #1
Opened 2017-02-21 22:31 UTC by pekrewrek

2017-02-21 23:49 UTC, provan requested changes

2017-02-21 23:49 UTC, provan commented on unicredit/main.js
> +        DeviceId: _deviceId,
_deviceId используется только здесь, не вижу смысла делать глобальную переменную.
можно просто вызывать здесь метод getDeviceId() без всяких переменных

2017-02-21 23:49 UTC, provan commented on unicredit/main.js
> +    var jsonResponse = xml2json(loginResponse);
может обернуть парсинг ответа в try..catch?
логировать ошибку и возвращать null?

2017-02-21 23:49 UTC, provan commented on unicredit/main.js
> +    ZenMoney.trace('SESSION_ID: ' + sessionId);
я б добавил проверку на отсутствие сессии и аварийный выход, чтоб не падать дальше с непонятными ошибками

2017-02-21 23:49 UTC, provan commented on unicredit/main.js
> +    ZenMoney.trace('SESSION_ID: ' + sessionId);
сессия каждый раз новая? не имеет смысла ее реюзать между запусками?

2017-02-21 23:49 UTC, provan commented on unicredit/main.js
> +            if (ZenMoney.getLevel() >= 13 && ZenMoney.isAccountSkipped(account.number)) {
копипаста детектед. ю хев 13 секондс ту ремув ит

2017-02-21 23:49 UTC, provan commented on unicredit/main.js
> +function processAccounts(sessionId) {
неудачное название. getAccounts() or loadAccounts()?

2017-02-21 23:49 UTC, provan commented on unicredit/main.js
> +var _appSettings;
зачем глобальная? используется только в майн

2017-02-21 23:49 UTC, provan commented on unicredit/main.js
> +            if (ZenMoney.getLevel() >= 13 && ZenMoney.isAccountSkipped(account.number)) {
как вариант - добавить сначала все акки в массив, а потом уже массив отфильтровать по id. в этом случае и пасты не будет и новые типы счетов проще добавлять будет. т.е. задача здесь - смаппить разные типы счетов к общему формату. а потом единая для всех обработка - в виде фильтрации на скип.

2017-02-21 23:49 UTC, provan commented on unicredit/main.js
> +function getDateString(date) {
вынести отсюда в файл с хелперами?

2017-02-21 23:49 UTC, provan commented on unicredit/main.js
> +function getDateString(date) {
formatDate()?

2017-02-21 23:49 UTC, provan commented on unicredit/main.js
> +    var lastSyncDate = ZenMoney.getData('last_sync', 0);
last_sync всегда будет 0, ты его не обновляешь

2017-02-21 23:49 UTC, provan commented on unicredit/main.js
> +function processTransactions(accounts, sessionId) {
я б назвал getTransactions(), убрал бы из параметра accounts и возвращал бы транзакции в json, а уже в майне, проверив на null вызвал бы метод updateTransactions.

ну а сюда соответственно проверку на ошибку получения и парсинга транзакций.

т.е. ответственность метода - загрузить список транзакций, не более

2017-02-21 23:49 UTC, provan commented on unicredit/main.js
> +        if (node.name != 'stmitem')
напиши коммент, почему мы пропускаем все, кроме stmitem, чтобы проще понять было.

2017-02-21 23:49 UTC, provan commented on unicredit/main.js
> +function updateTransactions(accounts, json) {
на методе след.ответственности: проход по циклу, конвертация одной транзакции, сохранение транзакции.
еще не хватает обработки ошибок.

я бы оставил ему ответственность обертки, а логику вынес бы в отдельный метод
что-то типа:
```
foreach tr in json
   try   
       var trans = convertTransaction(tr)
       result.push( trans )
   catch e
       log(e)

return result
```

а сохранение транзакций непосредственно в майн.
и туда же вынести сохранение аккаунтов.
в этом случае вся высокоуровневая логика будет сразу видна в майн:
```
var session = login()
var accounts = loadAccounts(session)
Zen.addAccounts( accounts )
var operations = loadOperations(session)
var transactions = processOperations( operations )
Zen.addTransactions( transactions )
```

2017-02-22 18:34 UTC, pekrewrek commented on unicredit/main.js
> +    ZenMoney.trace('SESSION_ID: ' + sessionId);
мне кажется нет, т.к. сессия довольно быстро протухает

2017-02-22 20:11 UTC, pekrewrek commented on unicredit/main.js
> +function getDateString(date) {
format имхо подразумевает, что мы можем этот формат задать, а мы не можем

2017-02-22 21:51 UTC, provan approved these changes

2017-02-22 21:51 UTC, provan commented on unicredit/main.js
> +    if (!accounts || accounts.length == 0)
сделай проверку сразу после получения, и убери ее из addAccounts()

2017-02-22 21:51 UTC, provan commented on unicredit/main.js
> +    ZenMoney.addAccount(accounts);
ай-ай-ай

2017-02-22 21:51 UTC, provan commented on unicredit/main.js
> +function getTransactions(accounts, json) {
json -> operations?

2017-02-22 22:38 UTC, merged